name: CI/CD for Flask App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint with flake8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache pip dependencies
      id: pip-cache  # <-- We assign an ID to reference later
      uses: actions/cache@v3
      with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
    - name: Install dependencies
      
      #install --upgrade pip: Tells pip to install the latest version of itself.
      #Using python -m pip makes sure the pip used matches the python you're running.
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Run flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest
    - name: create artifact to upload
      run: |
        mkdir -p uploaded/artifact
        echo hello > uploaded/artifact/world.txt
        echo hello world > uploaded/artifact/city.txt

    - uses: vimtor/action-zip@v1.2
        with:
          files: uploaded/artifact/*.txt
          dest: build.zip


    - name: to upload artifact
      uses: actions/upload-artifact@v4
                   
      with:
        name: my-artifact
        path: |
          uploaded/artifact/world.txt
          uploaded/artifact/city.txt
          ${{ github.workspace }}/build.zip

    
  docker:
    name: Build & Push Docker Image
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
