name: Build and Deploy Dockerized Flask App

on:
  #push:
    #branches: [ "main" ]  # Or change to your branch
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      docker_user:
        required: true
      docker_pass:
        required: true

    outputs:
      image_tag:
        description: "The Docker image tag"
        value: ${{ jobs.build.outputs.image_tag1 }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag1: ${{ steps.set_tag.outputs.tag }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.docker_user }}
        password: ${{ secrets.docker_pass }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.docker_user }}/flask-app:latest

    
    - id: set_tag
      run: |
        echo "tag=flask-app:${GITHUB_SHA::7}" >> $GITHUB_OUTPUT    
        echo $tag
  testvar:
    needs: build
    runs-on: ubuntu-latest
    steps:
       - run: |
          echo $tag
          echo $image_tag1
          echo $image_tag
          echo ${{github_sha::7}}
