name: A Pass variable via workflow dispatch

on: 
  push:

jobs:
  flowA:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger next workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: pass_variableBB.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: |
            commit_hash: ${{ github.sha }}
