name: passvariable in this workflow (recieving end)

on: 
  push:
  workflow_dispatch:
  workflow_run:
    workflows: [pass-variable-to-file]
    types:
      - completed

jobs:
  recieve_var:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: commit-info
          path: commit.txt
      
      - name: Read commit hash
        run: |
          COMMIT_HASH=$(cat commit.txt)
          echo "Commit: $COMMIT_HASH"
          echo "Variable successfully passed"

          
