name: A Pass variable via workflow dispatch

on: 
  push:
  

jobs:
  flowA:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Trigger next workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: pass_variableBB
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{"commit_hash": "${{ github.sha }}" }'
          ref: ${{ github.ref_name }}  #summary_AI  #main  # or another branch if needed.
            
