name: Add comment on PR
on: 
  pull_request: 
    types: [opened, reopened]

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    permissions: 
     pull-requests: write
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Hello world ! :wave:
            echo "$GITHUB_TOKEN"
            echo "$ORGANIZATION"
            echo "$REPOSITORY"
          reactions: eyes, rocket

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #ORGANIZATION: ${{ github.event.organization.login }}
          ORGANIZATION: ${{ github.event.repository.owner.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}

          
      - name: Check outputs
        run: |
          echo "id : ${{ steps.hello.outputs.id }}"
          echo "body : ${{ steps.hello.outputs.body }}"
          echo "html-url : ${{ steps.hello.outputs.html-url }}"
